/*
 * Kelompok 16
 */
package Form;


import Konfigurasi.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


/**
 *
 * @author kelompok 16
 */
public class logInMenu extends javax.swing.JFrame {

    /**
     * Creates new form logInMenu
     */
    public logInMenu() {
        initComponents();
               
        Connection conn; 
        conn = Koneksi.getConnection();
        //centre
        this.setLocationRelativeTo(null); 
        
        // border
       Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
       
       //border for closing button
       jLabel2_closeButton.setBorder(closeMin);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2_closeButton = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jPasswordField_logIn = new javax.swing.JPasswordField();
        jTextField1_userName = new javax.swing.JTextField();
        jButton1_LogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(249, 247, 247));

        jPanel2.setBackground(new java.awt.Color(145, 239, 198));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Log In");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setToolTipText("");

        jLabel2_closeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2_closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_closeButton.setText("X");
        jLabel2_closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_closeButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        password.setBackground(new java.awt.Color(255, 255, 255));

        userName.setBackground(new java.awt.Color(255, 255, 255));

        jPasswordField_logIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_logIn.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_logIn.setText("password");
        jPasswordField_logIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_logInFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_logInFocusLost(evt);
            }
        });
        jPasswordField_logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_logInActionPerformed(evt);
            }
        });

        jTextField1_userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1_userName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1_userName.setText("Account");
        jTextField1_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_userNameFocusLost(evt);
            }
        });

        jButton1_LogIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_LogIn.setText("Login");
        jButton1_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jPasswordField_logIn, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jTextField1_userName))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField_logIn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jButton1_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/lock.png")));
        userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/user_logIn.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 702, 564);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2_closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseEntered
        // TODO add your handling code here:
        
       Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
       
       //border for closing button
       jLabel2_closeButton.setBorder(closeMin);
       jLabel2_closeButton.setForeground(Color.red);
       
    }//GEN-LAST:event_jLabel2_closeButtonMouseEntered

    private void jLabel2_closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseExited
        // TODO add your handling code here:
       Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
       
       //border for closing button
       jLabel2_closeButton.setBorder(closeMin);
       jLabel2_closeButton.setForeground(Color.black);

        
    }//GEN-LAST:event_jLabel2_closeButtonMouseExited

    private void jPasswordField_logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_logInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_logInActionPerformed

    private void jTextField1_userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_userNameFocusGained
        // TODO add your handling code here:
        
        if(jTextField1_userName.getText().trim().equals("Account"))
        {
        jTextField1_userName.setText("");
        jTextField1_userName.setForeground(Color.black);
        
        }
        
    }//GEN-LAST:event_jTextField1_userNameFocusGained

    private void jTextField1_userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_userNameFocusLost
        // TODO add your handling code here:
        
        if (jTextField1_userName.getText().trim().equals("") || 
            jTextField1_userName.getText().trim().equals("Account") )
            
        {
            
            jTextField1_userName.setText("Account");
            jTextField1_userName.setForeground(new Color(153,153,153));
            
        }
        
        
    }//GEN-LAST:event_jTextField1_userNameFocusLost

    private void jPasswordField_logInFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_logInFocusGained
        // TODO add your handling code here:
        
        String LogInPassword = String.valueOf(jPasswordField_logIn.getPassword());
        
        if ( LogInPassword.trim().toLowerCase().equals("password"))
        {
            jPasswordField_logIn.setText("");
            jPasswordField_logIn.setForeground(Color.black);
                  
        }
            
        
    }//GEN-LAST:event_jPasswordField_logInFocusGained

    private void jPasswordField_logInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_logInFocusLost
        // TODO add your handling code here:
        
        String LogInPassword = String.valueOf(jPasswordField_logIn.getPassword());

        
        if (LogInPassword.trim().equals("") || 
            LogInPassword.trim().toLowerCase().equals("password") )
            
        {
            
            jPasswordField_logIn.setText("password");
            jPasswordField_logIn.setForeground(new Color(153,153,153));
            
        }
        
        
        
        
    }//GEN-LAST:event_jPasswordField_logInFocusLost

    private void jLabel2_closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_closeButtonMouseClicked

        // TODO add your handling code here:
        
        System.exit(0);
        
        
    }//GEN-LAST:event_jLabel2_closeButtonMouseClicked

    private void jButton1_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LogInActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement PreparedStatement;
        ResultSet ResultSet;
        new form_barang().TampilData();
        //get username
        String username = jTextField1_userName.getText();
        
        //get password
        String password = String.valueOf(jPasswordField_logIn.getPassword());
        
        //query to SQL database
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
                // show a message if the username or the password fields are empty
        if(username.trim().equals("username"))
        {
            new form_barang().TampilData();
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
        }
        else if(password.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        
    }//GEN-LAST:event_jButton1_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_closeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_logIn;
    private javax.swing.JTextField jTextField1_userName;
    private javax.swing.JLabel password;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
